# Generated by Django 4.2.6 on 2023-11-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_team'),
        ('tasks', '0004_task_author_task_deadline'),
    ]

    operations = [
    ]
