# Generated by Django 4.2.6 on 2023-11-22 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_team_id_remove_team_team_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
