# Generated by Django 4.2.6 on 2023-11-26 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(null=True, related_name='assigned_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
