# Generated by Django 4.2.6 on 2023-11-26 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(related_name='assigned_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
