# Generated by Django 4.2.6 on 2023-12-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_task_dependencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dependencies',
        ),
    ]
